// Reaction-tag feedback overlay. Pure module, no chrome.* APIs.
//
// Users tag a show with reasons it worked or didn't ("too slow",
// "soundtrack slaps"). Each reaction shifts the user's effective taste
// vector by a fraction of the show's own matched-tag contributions — so
// "dropped it" on a Slow Burn pick demotes Slow Burn everywhere the
// user sees it next, and "soundtrack slaps" nudges the matched tags up.
//
// Chip taxonomy lives in `reaction-data.js` (single source of truth,
// generated by scripts/build-reaction-data.mjs). Loaded here as a
// side-effect ESM import — it has no top-level export/import so the
// same file is also loadable as a classic content script for the UI.
// Either path lands the chip arrays on globalThis.__REACTION_DATA.
//
// Primary-group discipline: every chip has exactly one `group`. That's
// the only group it renders in, even if it could plausibly also speak
// to another residue (e.g. "depressing" could be feeling *or* takeaway
// — we keep it in feeling). Prevents the cross-group duplication the
// popup's axes[0] rule was designed to fix.
//
// Weight intensity tiers (polarity direction is in the sign):
//   Takeaway (dropped / rewatch / bounced-off / new-fave) — ±0.8 to ±1.0
//     strongest individual signal
//   Feeling / Story               — ±0.3 to ±0.5
//   Characters / Pacing           — ±0.3 to ±0.5
//   Craft                         — ±0.25 to ±0.4  smaller: craft axis
//     (studio/staff) isn't on the overlay yet, so a craft tag only
//     moves the show's story-tags today.
//   Neutral (😐)                  — ~60-70% of matching neg weight.
//
// Keywords are for search: typing "cry" should surface "tearjerker"
// and "wrecked me" without the user remembering exact labels.

import './reaction-data.js';

const _DATA = globalThis.__REACTION_DATA;
if (!_DATA) {
  throw new Error('[reactions] reaction-data.js did not populate globalThis.__REACTION_DATA — check load order');
}

export const CURATED_REACTIONS = _DATA.CURATED_REACTIONS;
export const EXTRA_REACTIONS   = _DATA.EXTRA_REACTIONS;
export const REACTION_TAGS     = _DATA.REACTION_TAGS;
export const REACTION_GROUPS   = _DATA.REACTION_GROUPS;
export const REACTION_SUBGROUPS = _DATA.REACTION_SUBGROUPS;

export const REACTION_TAGS_BY_KEY = Object.fromEntries(
  REACTION_TAGS.map(t => [t.key, t])
);


// A reaction with weight=1.0 on a top-matched tag (rank=100) moves the
// user's weight for that tag by ~0.15 before capping. Enough to shift
// downstream ranks noticeably without letting a single show's reactions
// dominate a heavily-loaded axis.
const BASE_INFLUENCE = 0.15;
const PER_TAG_CAP = 0.5;

// Input:
//   userReactions: { [aniListId]: { tags: string[], updatedAt } }
//   recsById:      { [aniListId]: { topTags: [{ tag, userWeight, rank }] } }
// Output: { [tagName]: delta }
export function computeReactionOverlay(userReactions, recsById) {
  const overlay = {};
  if (!userReactions || !recsById) return overlay;
  for (const [aniListId, entry] of Object.entries(userReactions)) {
    const tags = entry?.tags || [];
    const rec = recsById[aniListId];
    if (!rec || !tags.length) continue;
    const topTags = rec.topTags || [];
    if (!topTags.length) continue;
    for (const rkey of tags) {
      const r = REACTION_TAGS_BY_KEY[rkey];
      if (!r) continue;
      for (const m of topTags) {
        const rank = typeof m.rank === 'number' ? m.rank / 100 : 0.5;
        const d = r.weight * rank * BASE_INFLUENCE;
        overlay[m.tag] = (overlay[m.tag] || 0) + d;
      }
    }
  }
  for (const k of Object.keys(overlay)) {
    if (overlay[k] > PER_TAG_CAP) overlay[k] = PER_TAG_CAP;
    else if (overlay[k] < -PER_TAG_CAP) overlay[k] = -PER_TAG_CAP;
  }
  return overlay;
}
